app/controllers/episodes_controller.rb, app/controllers/season_summaries_controller.rb, app/controllers/shows_controller.rb
Now search and view TV show details without logging in
=> Whitelisted Shows->index,show actions and SeasonSummaries->index action

app/assets/stylesheets/application.scss
Super minor addition but makes it look cool
=> Logo smooth scrolls to top rated shows 🎉

app/views/shows/index.html.erb, app/views/shows/show.html.erb
**NOTE** No styling done on search page, but it now shows the correct image. Next step to use cards.
=> Corrected images

app/controllers/followed_shows_controller.rb, app/controllers/shows_controller.rb, app/models/episode.rb, app/models/show.rb, app/views/followed_shows/_form.html.erb, app/views/shared/_my_show_cards.html.erb, app/views/shows/show.html.erb, config/routes.rb, db/schema.rb, db/seeds.rb
=> Add to my shows

app/controllers/shows_controller.rb, app/views/shared/_my_show_cards.html.erb
Using proper images for my shows page
=> Images my shows

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_devise.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
Added padding under navbar and containers for devise pages
=> Navbar padding

app/assets/stylesheets/pages/_search.scss, app/controllers/shows_controller.rb, app/views/shows/index.html.erb
Created tabs like on figma design with streaming, rating and airing date info
=> Search page styling

app/controllers/application_controller.rb, app/controllers/reviews_controller.rb, app/controllers/shows_controller.rb, app/controllers/user_controller.rb, app/models/review.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/layouts/application.html.erb, app/views/reviews/_review_form.html.erb, app/views/shared/_my_reviews.html.erb, app/views/shared/_usernav.html.erb, app/views/shows/show.html.erb, app/views/user/show.html.erb, config/routes.rb, db/migrate/20211129173236_add_name_to_users.rb, db/schema.rb
Added reviews to 'Show' page and 'My Account' page
=> reviews done

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_searchbar.scss, app/assets/stylesheets/components/_usernav.scss, app/assets/stylesheets/pages/_account.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_search.scss, app/assets/stylesheets/shows/_show.scss, app/controllers/followed_shows_controller.rb, app/javascript/packs/style_navbar.js, app/views/pages/home.html.erb, app/views/reviews/_review_form.html.erb, app/views/reviews/_review_modal.html.erb, app/views/shared/_my_show_cards.html.erb, app/views/shared/_navbar.html.erb, app/views/shows/index.html.erb, app/views/shows/show.html.erb, app/views/user/show.html.erb
=> add frontend changes to searchpage 

app/controllers/followed_shows_controller.rb, app/views/shared/_my_reviews.html.erb, app/views/shared/_my_show_cards.html.erb
=> my review css

app/assets/stylesheets/components/_navbar.scss, app/controllers/followed_shows_controller.rb, app/controllers/notifications_controller.rb, app/controllers/season_summaries_controller.rb, app/javascript/components/add_show_popup.js, app/javascript/components/notifications.js, app/models/episode.rb, app/models/notification.rb, app/models/user.rb, app/views/notifications/_index.html.erb, app/views/notifications/index.json.jbuilder, app/views/shared/_navbar.html.erb, app/views/shows/index.html.erb, config/routes.rb, db/migrate/20211125165415_create_notifications.rb, db/migrate/20211129164257_add_notifiable_id_to_notifications.rb, db/migrate/20211129164329_add_notifiable_type_to_notifications.rb, db/migrate/20211130100205_add_episode_id_to_notifications.rb, db/schema.rb, db/seeds.rb, test/controllers/notifications_controller_test.rb, test/models/notification_test.rb
Notifications are working! 
I used the seed file to change one of the airing dates to today - if you want to see it, you may have to comment out the rest of the seed file, and uncomment the temp notifications section.
=> Notifications

public/404.html, public/500.html, public/styles.css
=> created 404 and 500 pages

app/assets/stylesheets/components/_searchbar.scss, app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> add change on navbar

app/assets/stylesheets/shows/_show.scss, app/controllers/shows_controller.rb, app/views/shows/show.html.erb
=> Show page edits

app/controllers/application_controller.rb, app/helpers/meta_tags_helper.rb, app/views/layouts/application.html.erb, config/initializers/default_meta.rb, config/meta.yml, db/schema.rb
Most of the checklist should work now - favicon is still an emoji so it doesn't pass the test but you can see it there.
=> changed meta tags and social meta tags

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_usernav.scss, app/assets/stylesheets/pages/_account.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_seasonepisodes.scss, app/assets/stylesheets/shows/_show.scss, db/schema.rb
Made all greens the same - can access using $green variable
=> Green consistency

app/assets/stylesheets/shows/_show.scss, app/views/shows/show.html.erb
Got rid of left margin on add to my shows button and change width to pixels to stop re-sizing
=> changed margin and width on buttons

app/assets/stylesheets/shows/_show.scss, app/views/shows/show.html.erb
Changed the css of how reviews are displaying - green stars, layout and font sizes
=> Reviews display

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_seasonindex.scss, app/assets/stylesheets/pages/_account.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_registration.scss, app/assets/stylesheets/pages/_search.scss, app/assets/stylesheets/pages/_seasonepisodes.scss, app/assets/stylesheets/shows/_show.scss, app/views/season_summaries/index.html.erb, app/views/shared/_navbar.html.erb, app/views/shows/show.html.erb
=> add changes to seasons page

app/assets/stylesheets/shows/_show.scss, app/views/shows/show.html.erb
=> add icon infront of review count

app/assets/stylesheets/pages/_account.scss, app/assets/stylesheets/pages/_search.scss, app/assets/stylesheets/shows/_show.scss, app/views/reviews/_review_modal.html.erb, app/views/shows/index.html.erb, app/views/shows/show.html.erb
=> changed paddings on showcards

app/assets/stylesheets/pages/_account.scss, app/views/shared/_my_show_cards.html.erb
Fixed error so it updates last watched episode. I also changed the message in the my show cards if you haven't started tracking - it sounded a bit developer-y before with "no progress so far"
=> Last watched my shows

app/views/layouts/application.html.erb
I just fixed the issue with body padding on the rest of the page apart from home page 👍
=> fixed body padding error

app/views/followed_shows/_form.html.erb, app/views/shows/show.html.erb
We were doing the check on whether to show the _Add to my shows_ button before validating a user is signed in. I changed it so that we check they're signed in before checking to display the button.
=> Show page accessible when logged out.

app/views/pages/home.html.erb
Caught this lil bug 🐞🪤  & fixed the in-page Telewise link which scrolls to top rated shows.
=> Dual sign up btn + Fix logo link

.gitignore, app/assets/stylesheets/components/_modal.scss, app/views/reviews/_review_form.html.erb, app/views/shared/_my_reviews.html.erb, app/views/shows/show.html.erb, node_modules/jquery-bar-rating/dist/themes/css-stars.css
Changed the stars to green, the review modal styling and ordered most recent reviews first
=> Review styling

db/seeds.rb
New ids in the seed array corresponding to
Squid Game 43687
Narcos 2705
The Witcher 28276
Power 299 
Hellbound 56942
The Crown 3594
You 3594
Cowboy Bebop 39892
Alex Rider 1871064
=> Seed file with 9 TV shows

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> add changes to navbar

app/assets/stylesheets/pages/_home.scss, app/controllers/users/confirmations_controller.rb, app/controllers/users/omniauth_callbacks_controller.rb, app/controllers/users/passwords_controller.rb, app/controllers/users/registrations_controller.rb, app/controllers/users/sessions_controller.rb, app/controllers/users/unlocks_controller.rb, app/views/pages/home.html.erb, config/routes.rb
Dummy account that allows users to get a sense of the site's features without signing up. This just needs to use the first record in our Users table. All data in the account is persistent and visible to anyone that accesses it.
=> Added guest account access
